version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - temporal
    networks:
      - temporal-network

  worker:
    build: .
    command: php worker.php
    volumes:
      - .:/app
    depends_on:
      - temporal
    networks:
      - temporal-network

  temporal:
    image: temporalio/auto-setup:1.22.3
    ports:
      - "7233:7233"
      - "8233:8233"
    environment:
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - ENABLE_ES=false
    networks:
      - temporal-network
    depends_on:
      - postgresql

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.3
    networks:
      - temporal-network
    depends_on:
      - temporal

  temporal-ui:
    image: temporalio/ui:2.21.3
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080
    networks:
      - temporal-network
    depends_on:
      - temporal

  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    networks:
      - temporal-network
    volumes:
      - postgresql-data:/var/lib/postgresql/data

networks:
  temporal-network:
    driver: bridge

volumes:
  postgresql-data: